app.controller('MainController', ['$scope', function($scope) { 
  $scope.projects=[
        {
            url:'',
            image:'css/images/ferrari.jpg'
        },
        {
            url:'',
            image:'css/images/unilever.jpg'
        },
        {
            url:'',
            image:'css/images/apple.jpg'
        },
        {
            url:'',
            image:'css/images/ferrari.jpg'
        },
        {
            url:'',
            image:'css/images/unilever.jpg'
        },
        {
            url:'',
            image:'css/images/apple.jpg'
        }
      ]}
]);

